from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from compress.common import BaselineHandle, CompressionRequest, shell_join
from src.registry import CheckpointRecord, load_checkpoint_index, save_checkpoint_index
from src.utils import dump_json, ensure_dir, project_path


@dataclass(slots=True)
class CompressionArtifact:
    artifact_id: str
    artifact_dir: str
    manifest_path: str
    log_path: str
    manifest: dict[str, Any]
    baseline_path: str | None = None
    command_path: str | None = None
    registered_name: str | None = None


def _relative_to_project(path: Path) -> str:
    return str(path.resolve().relative_to(project_path().resolve()))


def _write_command_script(
    artifact_dir: Path,
    baseline: BaselineHandle | None,
    command: list[str] | None,
) -> Path | None:
    if not command:
        return None
    script_path = artifact_dir / "planned_command.sh"
    lines = ["#!/usr/bin/env bash", "set -euo pipefail"]
    if baseline and baseline.path:
        lines.append(f"cd {baseline.path}")
    lines.append(shell_join(command))
    script_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return script_path


def save_artifact(
    request: CompressionRequest,
    *,
    baseline: BaselineHandle | None = None,
    command: list[str] | None = None,
    output_format: str = "transformers",
    status: str = "planned",
    ready_for_load: bool = False,
    notes: str = "",
    register: bool | None = None,
) -> CompressionArtifact:
    artifact_dir = ensure_dir(request.artifact_root / request.artifact_id)
    ensure_dir(artifact_dir / "weights")

    manifest = request.to_manifest_fields()
    manifest.update(
        {
            "output_dir": str(artifact_dir.resolve()),
            "output_format": output_format,
            "status": status,
            "ready_for_load": ready_for_load,
            "baseline": {
                "name": baseline.spec.display_name,
                "path": baseline.path,
                "origin": baseline.origin,
                "git_url": baseline.spec.git_url,
                "git_ref": baseline.spec.git_ref,
                "entrypoint": baseline.spec.entrypoint,
                "notes": baseline.spec.notes,
            }
            if baseline
            else None,
            "command": command,
            "notes": notes or request.notes,
        }
    )

    manifest_path = dump_json(manifest, artifact_dir / "manifest.json")
    log_payload = {
        "status": status,
        "ready_for_load": ready_for_load,
        "artifact_id": request.artifact_id,
        "command": command,
        "baseline_path": baseline.path if baseline else None,
    }
    log_path = dump_json(log_payload, artifact_dir / "compression_log.json")
    command_path = _write_command_script(artifact_dir, baseline, command)

    registered_name: str | None = None
    should_register = register if register is not None else request.register
    if should_register:
        if ready_for_load:
            registered_name = register_artifact(request, artifact_dir, enabled=request.enabled)
        else:
            warning_path = artifact_dir / "register_skipped.txt"
            warning_path.write_text(
                "Registration was skipped because the artifact is not yet marked ready_for_load.\n",
                encoding="utf-8",
            )

    return CompressionArtifact(
        artifact_id=request.artifact_id,
        artifact_dir=str(artifact_dir.resolve()),
        manifest_path=str(manifest_path),
        log_path=str(log_path),
        manifest=manifest,
        baseline_path=baseline.path if baseline else None,
        command_path=str(command_path) if command_path else None,
        registered_name=registered_name,
    )


def register_artifact(
    request: CompressionRequest,
    artifact_dir: Path,
    *,
    enabled: bool = False,
    index_path: str | Path | None = None,
) -> str:
    index_file = Path(index_path) if index_path else project_path("checkpoints", "index.csv")
    records = [record for record in load_checkpoint_index(index_file) if record.name != request.artifact_id]
    relative_subpath = _relative_to_project(artifact_dir)
    records.append(
        CheckpointRecord(
            name=request.artifact_id,
            model_family=request.model_slug,
            variant="generated",
            method=request.method,
            source="local",
            repo_id="",
            revision="",
            subpath=relative_subpath,
            benchmarks=["main", "speed"],
            enabled=enabled,
            notes=f"Generated by compress/{request.family}/{request.method}.",
        )
    )
    save_checkpoint_index(records, index_file)
    return request.artifact_id
